# Generated by Django 2.1 on 2018-08-11 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20180811_0716'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='email',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True, verbose_name='邮箱'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='gender',
            field=models.IntegerField(blank=True, choices=[(1, '男'), (2, '女')], null=True, verbose_name='签名'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='signature',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='签名'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='upload/images/avatar', verbose_name='头像'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='nickname',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='昵称'),
        ),
    ]
