# Generated by Django 2.1 on 2018-08-14 13:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0005_auto_20180811_2114'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(blank=True, max_length=200, null=True, verbose_name='留言内容')),
                ('creationTime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='留言时间')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name_plural': '用户留言',
            },
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='avatar',
            field=models.ImageField(blank=True, default='upload/images/avatar/default.jpg', null=True, upload_to='upload/images/avatar', verbose_name='头像'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='gender',
            field=models.IntegerField(blank=True, choices=[(1, '男'), (2, '女'), (0, '保密')], default=0, null=True, verbose_name='签名'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='nickname',
            field=models.CharField(blank=True, default='无名小辈', max_length=200, null=True, verbose_name='昵称'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='signature',
            field=models.CharField(blank=True, default='这位同学很懒，什么也没留下', max_length=200, null=True, verbose_name='签名'),
        ),
    ]
