# Generated by Django 2.1 on 2018-08-15 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20180815_2114'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True, verbose_name='职业')),
            ],
        ),
        migrations.AddField(
            model_name='userinfo',
            name='educations',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='学历'),
        ),
    ]
