# Generated by Django 2.1 on 2018-08-15 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20180815_2157'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='job',
            options={'verbose_name_plural': '职业'},
        ),
        migrations.RenameField(
            model_name='userinfo',
            old_name='educations',
            new_name='education',
        ),
        migrations.AddField(
            model_name='userinfo',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.Job', verbose_name='职业'),
        ),
    ]
