# Generated by Django 2.1 on 2018-08-15 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20180815_2204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='education',
            field=models.CharField(blank=True, choices=[(1, '大专'), (2, '本科'), (3, '硕士'), (4, '博士')], max_length=200, null=True, verbose_name='学历'),
        ),
    ]
